services:
    app:
        build: .
        container_name: shop_app
        restart: unless-stopped
        ports:
            - '8000:8000'
        depends_on:
            - db
        env_file: '.env'

    db:
        image: postgres:17.5-alpine
        container_name: shop_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        env_file: '.env'

volumes:
    postgres_data:
